### ISSUE TITLE
Add cron to automatically update the tree of life at a given frequency

### ISSUE THREAD

**Issue by damiendevienne** [Lifemap-ToL/lifemap-back#22]
Would be nice to automatize updates as before, setting an update every week (sunday, 2am) or everymonth? 
Receiving an email at the end of the process to know whether it went well or not could be useeful maybe.

**Comment by juba** [comment]
Cron should be in place. I scheduled it on monday 2AM, so that we would be rapidly available in case of problem (and we won't be bothered in the weekend).
